### ISSUE TITLE
Branch protection + deployment restriction

### ISSUE THREAD

**Issue by renefritze** [dune-community/Dockerfiles#27]
I'm planning to enable the same master branch protection scheme as in the dune-xt* modules here. Merging to master will only work with a PR. 
Non-master push builds on travis will also no longer actually deploy images to docker hub. This is in my opinion just a source of confusion with multiple living branches at the same time. 
Any objections, @dune-community/dune-xt-devs ?

**Comment by ftalbrecht** [comment]
None, go ahead. Good idea!
