### ISSUE TITLE
Qt download in debian-unstable broken

### ISSUE THREAD

**Issue by renefritze** [dune-community/Dockerfiles#33]
Seems to me the installer was taken offline/URL changed
https://travis-ci.org/dune-community/Dockerfiles/jobs/481404044#L617

**Comment by ftalbrecht** [comment]
On Fri, 2019-01-18 at 08:02 -0800, René Fritze wrote:
> Seems to me the installer was taken offline/URL changed
> https://travis-ci.org/dune-community/Dockerfiles/jobs/481404044#L617
> 

Seems they took the 4.2 release down for good. Can't find the file
elsewhere, anyone got any ideas?

And yes: this is exactly what you predicted... :/

**Comment by renefritze** [comment]
Was this a monolithic archive or did it download stuff at install time?

**Comment by ftalbrecht** [comment]
On Wed, 2019-01-23 at 10:18 -0800, René Fritze wrote:
> Was this a monolithic archive or did it download stuff at install
> time?
> 

The former. If we had that file, all would be fine.

**Comment by renefritze** [comment]
This is now blocking a PR of mine. Any progress towards a solution?

**Comment by renefritze** [comment]
fixed in #37
