### ISSUE TITLE
drop dailywork prefix

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/Dockerfiles#9]
The image names would just be `debian-minimal` or `dune-xt-functions-testing`. We could then drop the `dialywork` prefix from `docker_{exec,run}.sh`, which would allow me to easily spawn testing images locally using the same scripts...

**Comment by renefritze** [comment]
Is done only for testing and debian subdirs.

**Comment by renefritze** [comment]
That should've been all instances of the prefix.
